"""
Send BWDB tender report via email by any available method.
Tries: SMTP (if configured), .eml file, HTML file, mailto link.
"""
import sys, os, json, smtplib, webbrowser, subprocess
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))

# Load BWDB data
bwdb_path = Path("runtime/data_intel/bwdb_live_tenders.json")
data = json.loads(bwdb_path.read_text(encoding="utf-8"))
bwdb = data.get("bwdb_tenders", [])
total = data.get("total_tenders", 0)

# Build email content
html_rows = ""
txt_rows = ""
for t in bwdb:
    v = t.get("estimated_value_bdt", 0) or 0
    val_str = f"BDT {v:,.0f}" if v else "N/A"
    e = t.get("procuring_entity", "").replace(",,", ", ")
    html_rows += f"""
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #ddd;">{t['tender_id']}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #ddd;">{t['title'][:80]}...</td>
      <td style="padding:6px 10px;border-bottom:1px solid #ddd;">{e[:50]}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #ddd;text-align:right;">{val_str}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #ddd;">{t['deadline']}</td>
    </tr>"""
    txt_rows += f"  {t['tender_id']:>8} | {t['title'][:60]:<60} | {val_str:>15} | {t['deadline']}\n"

html_body = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head><body style="font-family:Arial,sans-serif;padding:20px;">
<h2 style="color:#1a5276;">BWDB Live Tenders Report</h2>
<p>Found <strong>{len(bwdb)}</strong> BWDB tenders out of {total} total live tenders on eGP portal.</p>
<p><em>Scraped at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</em></p>
<table style="border-collapse:collapse;width:100%;font-size:12px;">
<thead><tr style="background:#1a5276;color:white;">
  <th style="padding:8px 10px;text-align:left;">ID</th>
  <th style="padding:8px 10px;text-align:left;">Title</th>
  <th style="padding:8px 10px;text-align:left;">Entity</th>
  <th style="padding:8px 10px;text-align:right;">Value</th>
  <th style="padding:8px 10px;text-align:left;">Deadline</th>
</tr></thead><tbody>
{html_rows}
</tbody></table>
<p style="margin-top:20px;color:#888;font-size:11px;">Generated by Procurement Flow Specialist BD</p>
</body></html>"""

txt_body = f"""BWDB Live Tenders Report
{'='*70}
Found {len(bwdb)} BWDB tenders out of {total} total live tenders.

{txt_rows}
Generated by Procurement Flow Specialist BD
"""

subject = f"BWDB Live Tenders Report - {len(bwdb)} tenders found"

savedir = Path("runtime/data_intel")
savedir.mkdir(parents=True, exist_ok=True)
ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

# ── Method 1: Save .eml file (opens in Outlook/Mail) ──
msg = MIMEMultipart("alternative")
msg["Subject"] = subject
msg["From"] = "himel09073@gmail.com"
msg["To"] = "z.nasim073@gmail.com"
msg.attach(MIMEText(txt_body, "plain", "utf-8"))
msg.attach(MIMEText(html_body, "html", "utf-8"))

eml_path = savedir / f"bwdb_report_{ts}.eml"
with open(eml_path, "wb") as f:
    f.write(msg.as_bytes())
print(f"[1/4] Saved .eml: {eml_path}")

# ── Method 2: Save HTML file (open in browser) ──
html_path = savedir / f"bwdb_report_{ts}.html"
html_path.write_text(html_body, encoding="utf-8")
print(f"[2/4] Saved HTML: {html_path}")

# ── Method 3: Save plain text ──
txt_path = savedir / f"bwdb_report_{ts}.txt"
txt_path.write_text(txt_body, encoding="utf-8")
print(f"[3/4] Saved TXT: {txt_path}")

# ── Method 4: Try SMTP (if .env has credentials) ──
smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
smtp_port = int(os.getenv("SMTP_PORT", "587"))
smtp_user = os.getenv("SMTP_USER", "")
smtp_pass = os.getenv("SMTP_PASS", "")

sent = False
if smtp_user and smtp_pass:
    try:
        server = smtplib.SMTP(smtp_host, smtp_port, timeout=30)
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, ["z.nasim073@gmail.com"], msg.as_string())
        server.quit()
        print(f"[4/4] Email SENT via SMTP to z.nasim073@gmail.com")
        sent = True
    except Exception as e:
        print(f"[4/4] SMTP failed: {e}")
else:
    print(f"[4/4] SMTP not configured — set SMTP_USER and SMTP_PASS in .env")

if not sent:
    print(f"\n{'='*60}")
    print(f"EMAIL NOT SENT — SMTP credentials missing.")
    print(f"To send manually:")
    print(f"  1. Open {html_path} in your browser")
    print(f"  2. Select all (Ctrl+A) and copy (Ctrl+C)")
    print(f"  3. Paste into Gmail compose to z.nasim073@gmail.com")
    print(f"  OR double-click the .eml file to open in mail client")
    print(f"{'='*60}")

print("\nDONE")
