"""Try every possible method to send the BWDB email."""
import sys, os, json, smtplib
from pathlib import Path
from email.mime.text import MIMEText

sys.path.insert(0, os.path.dirname(__file__))

bwdb = json.loads(Path("runtime/data_intel/bwdb_live_tenders.json").read_text(encoding="utf-8"))
bwdb_list = bwdb.get("bwdb_tenders", [])

rows = ""
for t in bwdb_list:
    v = t.get("estimated_value_bdt", 0) or 0
    rows += "  {} | BDT {:>8,.0f} | {} | {}\n".format(
        t["tender_id"], v, t["deadline"], t["procuring_entity"][:50]
    )

body = "BWDB Live Tenders Report\n" + "="*70 + "\n"
body += f"Found {len(bwdb_list)} BWDB live tenders\n\n"
body += rows
body += "\n\nGenerated by Procurement Flow Specialist BD"

# Build MIME message
msg = MIMEText(body, "plain", "utf-8")
msg["Subject"] = f"BWDBLiveTenders-{len(bwdb_list)}found"
msg["From"] = "procurement@flow.local"
msg["To"] = "z.nasim073@gmail.com"

# Method 1: Try SMTP with any configured credentials
env_user = os.getenv("SMTP_USER", "")
env_pass = os.getenv("SMTP_PASS", "")
sent = False

if env_user and env_pass:
    for host, port in [("smtp.gmail.com", 587), ("smtp.gmail.com", 465)]:
        try:
            if port == 465:
                server = smtplib.SMTP_SSL(host, port, timeout=15)
            else:
                server = smtplib.SMTP(host, port, timeout=15)
                server.starttls()
            server.login(env_user, env_pass)
            server.sendmail(env_user, ["z.nasim073@gmail.com"], msg.as_string())
            server.quit()
            print(f"EMAIL SENT via {host}:{port} using {env_user}")
            sent = True
            break
        except Exception as e:
            print(f"SMTP {host}:{port} failed: {e}")

# Method 2: Try without auth (some local relays)
if not sent:
    for host, port in [("localhost", 25), ("127.0.0.1", 25)]:
        try:
            server = smtplib.SMTP(host, port, timeout=5)
            server.sendmail("noreply@local", ["z.nasim073@gmail.com"], msg.as_string())
            server.quit()
            print(f"EMAIL SENT via {host}:{port} (no auth)")
            sent = True
            break
        except Exception:
            pass

# Method 3: Save as .eml and open with default mail app
if not sent:
    eml_path = Path("runtime/data_intel") / "BWDB_Tenders_Report.eml"
    eml_path.write_text(msg.as_string(), encoding="utf-8")
    print(f"\nSMTP unavailable — saved .eml file:")
    print(f"  {eml_path.resolve()}")
    print(f"\nTo send via Gmail:")
    print(f"  1. Open: start {eml_path}")
    print(f"  2. Or drag into Gmail compose window")
    print(f"\nTo configure SMTP, add to .env:")
    print(f'  SMTP_USER=himel09073@gmail.com')
    print(f'  SMTP_PASS=your-16-char-app-password')
    print(f'\nApp passwords: https://myaccount.google.com/apppasswords')

print("\nDone")
